### ISSUE TITLE
Find If a Value Exist in a Sorted Array

### ISSUE THREAD

**Issue by RoyiAvital** [stgatilov/linear-vs-binary-search#1]
How could one expand the Binary Search in order to get a simple binary answer, does the input values exist in the given sorted array?

Thank You.

**Comment by stgatilov** [comment]
Take `linear_search_sse` function, replace `_mm_cmplt_epi32` with `_mm_cmpeq_epi32`.
At the end of the function, `return _mm_cvtsi128_si32(cnt);` will return how many times given value occurs in the array.

**Comment by RoyiAvital** [comment]
What about a specific code for the case of no power of 2?
What about the existence for Binary Search?
